name: .NET

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: dotnet restore
        run: dotnet restore
      - name: Install dependencies
        run: |
          dotnet new tool-manifest --force
          dotnet tool install paket
          dotnet tool restore
          dotnet paket init
          dotnet paket install
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
