name: .NET

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dependencies
        uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518
      - name: Install dependencies
        run: paket install
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
